### ISSUE TITLE
Great linter! Just one question about %w vs %v

### ISSUE THREAD

**Issue by iangregsondev** [tomarrell/wrapcheck#18]
Hi,

Forgive my question but I think there is a reason you are using %v rather than %w on errorf to wrap errors but I am not sure I understand it.

I have always been using %w with returning to new errors that wrap previous ones but I notice here you are using %v.

What is the reason ?

Thanks again!

**Comment by tomarrell** [comment]
G'day @iangregsondev. Yes, I primarily choose to compose errors with `%v` as a debugging tool when I don't need error inspection, which is the majority of the time. 

Wrapping using `%w` causes the underlying error to now be exposed as part of the package's API. This should be a conscious decision, as once some functionality depends on the underlying error type, any modification to the underlying error chain is a breaking change.

Therefore, using `%v` _until_ you know that you need to inspect the error and are willing to support it is a sensible heuristic I recommend.

You can also read the advice from the Go blog, [https://blog.golang.org/go1.13-errors#TOC_3.4.](https://blog.golang.org/go1.13-errors#TOC_3.4.), where they echo a similar sentiment.

> In other words, wrapping an error makes that error part of your API. If you don't want to commit to supporting that error as part of your API in the future, you shouldn't wrap the error.

I hope that helps. Let me know if you have any further questions.

**Comment by arpanetus** [comment]
just as the error mentioned above, is there any way to customize/modify the wrapcheck (would you accept the merge request if I send it?)

**Comment by tomarrell** [comment]
Hello, yes there are currently two ways to modify the behaviour of wrapcheck. You can set either `ignoreSigs` to ignore certain signatures from being reported as unwrapped, or you can ignore reports from package globs given the `ignorePackageGlobs` option.

Could you describe the functionality that you are missing?

```yaml
# An array of strings which specify substrings of signatures to ignore. If this
# set, it will override the default set of ignored signatures. You can find the
# default set at the top of ./wrapcheck/wrapcheck.go.
ignoreSigs:
- .Errorf(
- errors.New(
- errors.Unwrap(
- .Wrap(
- .Wrapf(
- .WithMessage(
- .WithMessagef(
- .WithStack(

# An array of glob patterns which, if any match the package of the function
# returning the error, will skip wrapcheck analysis for this error. This is
# useful for broadly ignoring packages and/or subpackages from wrapcheck
# analysis. There are no defaults for this value.
ignorePackageGlobs:
- encoding/*
- github.com/pkg/*
```
