### ISSUE TITLE
Support for ignoring regular match files

### ISSUE THREAD

**Issue by shuqingzai** [tomarrell/wrapcheck#41]
For example, the methods in a `bootstrap.go` are all used to start the program, and I just want to process them uniformly at the location where the service starts, instead of wrapping each function

![image](https://github.com/tomarrell/wrapcheck/assets/44406033/51dff958-b4ef-4a4d-8bd3-92fac940aba0)

**Comment by tomarrell** [comment]
G'day @shuqingzai, thanks for the suggestion. 

Are you using golangci-lint? If you are, you can exclude certain linters reporting errors for specific files using exclude rules.

https://golangci-lint.run/usage/configuration/

e.g. 

```
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
```
