### ISSUE TITLE
Proposal: ignore returning value of specify package's function

### ISSUE THREAD

**Issue by sanposhiho** [tomarrell/wrapcheck#8]
Hello 👋 
Thank you for developing such a great tool!

I'm using a library that wraps and manages errors like below.

https://github.com/morikuni/failure
https://github.com/pkg/errors

Currently, wrapcheck also reports for these librarie's function.

example 

```
error returned from external package is unwrapped (wrapcheck)
                return nil, errors.Wrap(err, "failed to do something")
                                  ^
```

This is, of course, the correct behavior. But I don't need these report from wrapcheck.
So, I ignore these reports with golangci-lint's exclude-rules like below.

```
issues:
  exclude-rules:
   - source: "errors"
      linters:
        - wrapcheck
    - source: "failure"
      linters:
        - wrapcheck
```

https://golangci-lint.run/usage/configuration/

It would be very helpful to be able to configure these settings on the wrapcheck side.

(This proposal may be similar to #2)

Thanks
